core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('profile/<slug:username>/', views.profile, name='profile'),
    path('profile/<slug:username>/edit/',
         views.update_user, name='profile_edit'),
    path('', views.home, name='home'),
]

poster/urls.py
from django.urls import path, include
from . import views

app_name = 'poster'

urlpatterns = [
    path(
        'conferences/',
        views.ConferenceIndexView.as_view(),
        name='conference_index'
    ),
    path(
        'conferences/<int:conf_k>/',
        views.conference_detail,
        name='conference_detail'
    ),
    path(
        'conferences/<int:conf_k>/posters/<int:poster_pk>/',
        views.poster_detail,
        name='poster_detail'
    ),
    path(
        'conferences/<int:conf_k>/posters/create/',
        views.poster_update,
        name='poster_create'
    ),
    path(
        'conferences/<int:conf_k>/posters/<int:poster_pk>/update',
        views.poster_update,
        name='poster_update'
    ),
]

posterchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('conferences/', include('poster.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import re

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from PIL import Image


def validate_name(name: str):
    """Ensures that names for users comply with PosterChat."""
    if name.startswith('-') or name.endswith('-'):
        msg = "%(name)s cannot start or end with '-'."
    elif name.startswith(' ') or name.endswith(' '):
        msg = "%(name)s cannot start or end with spaces."
    elif not re.match(r'^[A-Za-z-\s]+$', name):
        msg = "%(name)s can only have letters, and hyphen."
    elif re.match(r'.*[-]{2,}.*', name):
        msg = "%(name)s cannot have multiple '-' in a row."
    elif re.match(r'.*[\s]{2,}.*', name):
        msg = "%(name)s cannot have multiple spaces in a row."
    else:
        return
    raise ValidationError(_(msg), "invalid_name", {"name": name})


def validate_username(name: str):
    """Ensures that usernames comply with PosterChat's requirements."""
    validators.RegexValidator(r'^[A-Za-z\d_]+$', )

    if not re.match(r'^[A-Za-z\d_]+$', name):
        msg = _("Only allowed letters, numbers and underscore.")
    elif len("".join(letter for letter in name if letter.isalnum())) < 5:
        msg = "%(name)s must be at least 5 alphanumeric chars long."
    elif name[0].isdigit():
        msg = "%(name)s cannot start with a number.",
    elif name.startswith('_') or name.endswith('_'):
        msg = "%(name)s cannot start or end with underscore."
    elif re.match(r'.*[_]{2,}.*', name):
        msg = "%(name)s cannot have multiple '_' in a row."
    else:
        return

    raise ValidationError(_(msg), "invalid_username", {"name": name})


class UserManager(BaseUserManager):
    """Implements Django user manager to use the custom user in PosterChat

    Django expects UserManager interface as such:
    https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#writing-a-manager-for-a-custom-user-model
    """

    def create_user(self, email, first_name, last_name, username, password=None, commit=True, **extra_kwargs):

        if not email:
            raise ValueError(_("Users must have an email address"))

        if not first_name:
            raise ValueError(_('Users must have a first name'))

        if not last_name:
            raise ValueError(_("Users must have a last name"))

        if not username:
            raise ValueError(_("Users must have a username"))

        user = self.model(email=self.normalize_email(email), first_name=first_name,
                          last_name=last_name, username=username, **extra_kwargs)
        user.set_password(password)

        if commit:
            user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, username, password):
        user = self.create_user(email, password=password, first_name=first_name,
                                last_name=last_name, username=username, commit=False)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Implements Django user for use in PosterChat

    Django expects User models to support the following interface
    https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#specifying-a-custom-user-model
    """

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["first_name", "last_name", "username"]

    email = models.EmailField(verbose_name=_("email address"),
                              max_length=255, unique=True)

    first_name = models.CharField(_("first name"), max_length=30,
                                  blank=True, validators=[validate_name])
    last_name = models.CharField(_("last name"), max_length=150,
                                 blank=True, validators=[validate_name])

    username = models.SlugField(_("user name"), max_length=16, unique=True,
                                validators=[])

    # Optional fields
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_("Use this to delete accounts. Inactive (False) accounts should be treated as if they're deleted."))

    is_staff = models.BooleanField(_("staff status"), default=False,
                                   help_text=_("If True, user can log into the admin site."))

    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    avatar = models.ImageField(
        "Profile Image", blank=True, upload_to="avatar_images")

    description = models.TextField("Bio", blank=True)

    objects = UserManager()

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}".strip()

    def get_short_name(self):
        return self.first_name.strip()

    def __str__(self):
        return f"{self.get_full_name()} <{self.email}>"

    def save(self, *args, **kwargs):
        """Overloads save method to resize avatar on save"""
        super().save(*args, **kwargs)
        if self.avatar:
            img = Image.open(self.avatar.path)

            if img.height > 200 or img.width > 200:
                img.thumbnail((200, 200))
                img.save(self.avatar.path)
                super().save()

    def clean(self):
        """Performs pre-db validation on several fields."""
        super().clean()
        validate_name(self.first_name)
        validate_name(self.last_name)
        validate_username(self.username)

core/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class AdminAddUserForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',
                  "username", "avatar", "description",)

    def clean_password2(self):
        """Checks that the two passwords match
        """

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do no match")

        return password2

    def save(self, commit=True):
        user = super().save(commit=False)

        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()

        return user


class AdminUpdateUserForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = (
            "email", "password", "first_name", "last_name", "username", "is_active", "is_staff", "avatar", "description",
        )

    def clean_password(self):
        return self.initial["password"]


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name",
                  "username", "avatar", "description")

core/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model, decorators
from django.http import HttpResponseRedirect

from .forms import UpdateUserForm


@decorators.login_required
def profile(request, username):
    template_name = "core/profile.html"
    profile = get_object_or_404(get_user_model(), username=username)
    return render(request, template_name, {"profile": profile})


def home(request):
    template_name = "core/home.html"
    return render(request, template_name, {})


@decorators.login_required
def update_user(request, username):
    if request.method == "POST":
        user = UpdateUserForm(request.POST)
        if user.is_valid():
            return HttpResponseRedirect("/")

    else:
        profile = get_object_or_404(get_user_model(), username=username)
        context = {"profile": profile}

        form = UpdateUserForm(instance=request.user)
        context["form"] = form

        return render(request, "core/profile_edit.html", context)

core/templates/core/home.html
{% extends 'base.html' %} {% block content %}
<div
  class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light"
>
  <div class="col-md-6 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">Online Conference Platform</h1>
    <p class="lead font-weight-normal">
      Host and attend world class conferences from the comfort of your home.
    </p>
    <a class="btn btn-outline-secondary" href="#">Get Started</a>
  </div>
  <div class="product-device box-shadow d-none d-md-block"></div>
  <div
    class="product-device product-device-2 box-shadow d-none d-md-block"
  ></div>
</div>
<div class="container marketing">
  <div class="mx-auto text-center p-3">
    <h2>Connect innovative ideas with PosterChat</h2>
  </div>
  <div class="row">
    <div class="container" style="padding: 50px;">
      <div class="row text-center">
        <div class="col-sm">
          <i class="fa fa-5x fa-lightbulb-o row" style="padding: 15px;"></i>
          <h5>Attend popular conferences</h5>
          <p>
            in topics such as artificial intellgience, neuroscience, material
            science, and more!
          </p>
          <a class="btn btn-secondary" href="{% url 'poster:conference_index' %}" role="button"
            >Browse Conferences »</a
          >
        </div>
        <div class="col-sm">
          <i class="fa fa-5x fa-users row" style="padding: 15px;"></i>
          <h5>Reach large audiences</h5>
          <p>
            by making your research posters available for an online community.
          </p>
          <a class="btn btn-secondary" href="#" role="button"
            >View Case Study »</a
          >
        </div>
        <div class="col-sm">
          <i class="fa fa-5x fa-microscope row" style="padding: 15px;"></i>
          <h5>Host your own conferences</h5>
          <p>
            Did we mention it's free?
          </p>
          <a class="btn btn-secondary" href="#" role="button"
            >Host a Conference »</a
          >
        </div>
      </div>
    </div>
  </div>

  {% endblock %}
</div>

core/templates/core/profile.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="">
    <img class="rounded-circle-account-img" src="{{ profile.avatar.url }}" />
    <div class="media-body">
      <h2>{{ profile.first_name }} {{ profile.last_name }}</h2>
      <h2 class="account-heading">{{ profile.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
      <p>{{ profile.description }}</p>
    </div>
    {% if user.username == profile.username %}
    <a
      href="{% url 'core:profile_edit' profile.username %}"
      class="btn btn-sm btn-secondary"
      >Edit</a
    >
    {% endif %}
  </div>
</div>
{% endblock %}

core/templates/core/profile_edit.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}

{% if user.username == profile.username %}
  <div class="container">
    <form method="post" style="margin-top: 1.3em;">
        {{ form | crispy }} {% csrf_token %}
        <button class="btn btn-primary" type="submit">Submit changes</button>
      </form>
  </div>
{% endif %}
{% endblock %}