core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('profile/<slug:username>/', views.profile, name='profile'),
    path('profile/<slug:username>/edit/',
         views.update_user, name='profile_edit'),
    path('', views.home, name='home'),
]

poster/urls.py
from django.urls import path, include
from . import views

app_name = 'poster'

urlpatterns = [
    path(
        'conferences/',
        views.ConferenceIndexView.as_view(),
        name='conference_index'
    ),
    path(
        'conferences/<int:conf_k>/',
        views.conference_detail,
        name='conference_detail'
    ),
    path(
        'conferences/<int:conf_k>/posters/<int:poster_pk>/',
        views.poster_detail,
        name='poster_detail'
    ),
    path(
        'conferences/<int:conf_k>/posters/create/',
        views.poster_update,
        name='poster_create'
    ),
    path(
        'conferences/<int:conf_k>/posters/<int:poster_pk>/update',
        views.poster_update,
        name='poster_update'
    ),
]

posterchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('conferences/', include('poster.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <script src="https://kit.fontawesome.com/1003b16e34.js" crossorigin="anonymous"></script>

    <title>PosterChat</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'core:home' %}">PosterChat</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:home' %}"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'poster:conference_index' %}">Conferences</a>
            </li>
          </ul>
          {% if user.is_anonymous %}
            <a class="btn btn-outline-success my-2 mr-sm-2 my-sm-0" href="{% url 'account_login' %}" type="submit">Log In</a>
            <a class="btn btn-success my-2 my-sm-0" type="submit" href="{% url 'account_signup' %}">Sign Up</a>
          {% else %}
            <a class="btn btn-outline-success my-2 mr-sm-2 my-sm-0" href="{% url 'core:profile' user.username %}" type="submit">Profile</a>
            <a class="btn btn-outline-success my-2 mr-sm-2 my-sm-0" href="{% url 'account_logout' %}" type="submit">Log Out</a>
          {% endif %}
        </div>
      </nav>
    </header> 
    <br>
    <main role="main">

        {% block content %}{% endblock %}

    <footer class="footer">
      <div class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <span>
          © 2020 PosterChat · <a href="#">Privacy</a> ·
          <a href="#">Terms</a>
        </span>
      </div>
    </footer>
    </main>
      
    </div>
    
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script>
      window.jQuery ||
        document.write(
          '<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>'
        );
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>