core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path('profile/<slug:username>/', views.profile, name='profile'),
    path('profile/<slug:username>/edit/',
         views.update_user, name='profile_edit'),
    path('', views.home, name='home'),
]

poster/urls.py
from django.urls import path, include
from . import views

app_name = 'poster'

urlpatterns = [
    path(
        'conferences/',
        views.ConferenceIndexView.as_view(),
        name='conference_index'
    ),
    path(
        'conferences/<int:conf_k>/',
        views.conference_detail,
        name='conference_detail'
    ),
    path(
        'conferences/<int:conf_k>/posters/<int:poster_pk>/',
        views.poster_detail,
        name='poster_detail'
    ),
    path(
        'conferences/<int:conf_k>/posters/create/',
        views.poster_update,
        name='poster_create'
    ),
    path(
        'conferences/<int:conf_k>/posters/<int:poster_pk>/update',
        views.poster_update,
        name='poster_update'
    ),
]

posterchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('conferences/', include('poster.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poster/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from core.models import User
from typing import List


class Conference(models.Model):
    title = models.CharField(max_length=50)
    institution = models.CharField(max_length=50)
    description = models.TextField()

    organizers = models.ManyToManyField(
        get_user_model(), related_name="organizers")
    attendees = models.ManyToManyField(
        get_user_model(), related_name="attendees")
    guests = models.ManyToManyField(get_user_model(), related_name="guests")

    created_date = models.DateTimeField('created date', auto_now=True)
    is_public = models.BooleanField(
        "is conference publically accessible", default=True)

    def update_organizers(self):
        if self.organizers != self._original_organizers:
            self.update_group(new_organizers, "organizers")
            self._original_organizers = self.organizers

        if self.attendees != self._original_attendees:
            self.update_group(new_attendees, "attendees")
            self._original_attendees = self.attendees

        if self.guests != self._original_guests:
            self.update_group(new_guests, "guests")
            self._original_guests = self.guests

    def update_group(self, new_users: List[User], group_name: str):
        current_users = getattr(self, group_name)

        group = getattr(self, group_name + "_group")

        to_rem = [o for o in current_users if o not in new_users]
        to_add = [o for o in new_users if o not in current_users]

        for o in to_rem:
            group.user_set.remove(o)

        for o in to_add:
            group.user_set.add(o)

    def __str__(self):
        return self.title


class Poster(models.Model):
    image = models.ImageField(blank=True, null=True)
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=50)
    authors = models.ManyToManyField(User)
    description = models.TextField()
    created_date = models.DateTimeField('created date')
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    poster = models.ForeignKey(Poster, on_delete=models.CASCADE)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    body = models.TextField()
    created_date = models.DateTimeField('created date', auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_date']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

poster/forms.py
from django import forms
from .models import Poster, Comment


class PosterForm(forms.ModelForm):
    class Meta:
        model = Poster
        fields = ('title', 'subtitle', 'description', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

poster/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth import decorators
from django.views import generic
from .models import Poster, Conference
from .forms import CommentForm, PosterForm
from PIL import Image
import datetime


class ConferenceIndexView(generic.ListView):
    template_name = "poster/conference_index.html"
    queryset = Conference.objects.all()
    context_object_name = 'latest_conferences'

    def get_queryset(self):
        return Conference.objects.order_by('-created_date')[:100]


@decorators.login_required
def conference_detail(request, conf_k):
    template_name = "poster/conference_detail.html"
    conference = get_object_or_404(Conference, pk=conf_k)

    posters = conference.poster_set.all()

    organizers = conference.organizers.all()
    attendees = conference.attendees.all()
    guests = conference.attendees.all()

    is_organizer = request.user.is_authenticated and request.user in organizers

    return render(request, template_name, {
        "conference": conference,
        "posters": posters,
        "organizers": organizers,
        "attendees": attendees,
        "guests": guests,
        "is_organizer": is_organizer,
    })


@decorators.login_required
def poster_create(request, conf_k):
    template_name = "poster/poster_create.html"
    context = {}

    if request.method == "POST":
        poster_form = PosterForm(data=request.POST, files=request.FILES)
        conference = get_object_or_404(Conference, pk=conf_k)
        if poster_form.is_valid():
            new_poster = poster_form.save(commit=False)
            # new_poster.authors.add(request.user)
            new_poster.created_date = datetime.datetime.now()
            new_poster.conference = conference

            destination = new_poster.image.path

            new_poster.save()
        return HttpResponseRedirect("/")

    else:
        form = PosterForm()
        context["form"] = form
        return render(request, template_name, context)


@decorators.login_required
def poster_update(request, conf_k, poster_pk=None):
    template_name = "poster/poster_create.html"
    context = {}

    if request.method == "POST":
        poster_form = PosterForm(data=request.POST, files=request.FILES)
        conference = get_object_or_404(Conference, pk=conf_k)
        if poster_form.is_valid():
            new_poster = poster_form.save(commit=False)
            # new_poster.authors.add(request.user)
            new_poster.created_date = datetime.datetime.now()
            new_poster.conference = conference

            new_poster.save()
        return HttpResponseRedirect("/")

    elif poster_pk:
        poster = get_object_or_404(Poster, pk=poster_pk)
        context["poster"] = poster
        form = PosterForm(instance=poster)
    else:
        form = PosterForm()

    context["form"] = form
    return render(request, template_name, context)


@decorators.login_required
def poster_detail(request, conf_k, poster_pk):
    template_name = 'poster/poster_detail.html'
    poster = get_object_or_404(Poster, pk=poster_pk)
    conference = get_object_or_404(Conference, pk=conf_k)

    comments = poster.comment_set.filter(active=True)

    organizers = conference.organizers.all()
    attendees = conference.attendees.all()
    guests = conference.attendees.all()
    authors = poster.authors.all()

    is_editable = request.user in organizers or request.user in authors
    can_comment = request.user in organizers or request.user in attendees or request.users in authors

    new_comment = None
    if request.method != "POST":
        comment_form = CommentForm()
    else:
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object

            new_comment = comment_form.save(commit=False)
            new_comment.poster = poster
            new_comment.author = request.user
            new_comment.save()

    return render(request, template_name, {
        "poster": poster,
        "conference": conference,
        "comments": comments,
        "new_comment": new_comment,
        "comment_form": comment_form,
        "is_editable": is_editable,
        "can_comment": can_comment,
    })

poster/templates/poster/conference_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>Organizers</h1>
  {% for organizer in organizers %}
    <a href="{% url 'core:profile' organizer.username %}">{{ organizer.first_name }} {{ organizer.last_name }}</a>
  {% endfor %}

  <h1>Attendees</h1>
  {% for attendee in attendees %}
    <a href="{% url 'core:profile' attendee.username %}">{{ attendee.first_name }} {{ attendee.last_name }}</a>
  {% endfor %}

  {% if posters %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Poster</th>
        <th scope="col">Subtitle</th>
        <th scope="col">Publish Date</th>
      </tr>
    </thead>
    <tbody>
      {% for poster in posters %}
      <tr>
        <td>
          <a href="{% url 'poster:poster_detail' conference.id poster.id %}"
            >{{ poster.title }}</a
          >
        </td>
        <td>{{ poster.subtitle }}</td>
        <td>{{ poster.created_date }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>No posters are available.</p>
  {% endif %} 

  {% if is_organizer %}
    <a class="btn btn-md btn-primary" href="{% url 'poster:poster_create' conference.pk %}">Add new</a>
  {% endif %}
</div>

{% endblock %}

poster/templates/poster/conference_index.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  {% if latest_conferences %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Conference</th>
        <th scope="col">Institution</th>
        <th scope="col">Publish Date</th>
      </tr>
    </thead>
    <tbody>
      {% for conference in latest_conferences %}
      <tr>
        <td>
          <a href="{% url 'poster:conference_detail' conference.id %}"
            >{{ conference.title }}</a
          >
        </td>
        <td>{{ conference.institution }}</td>
        <td>{{ conference.created_date }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No conferences are available.</p>
  {% endif %}
</div>

{% endblock %}

poster/templates/poster/post_list_3.html
{% extends 'poster/base.html' %}
{% block content %}
<img src="/media/cylinder.png">
<!-- 	{% for post in posts %} -->
	<br>
	
	<div class="card">
		<div class="card_header">
			<div class="profile_image">
				
			</div>
			<div class="post_info">
				<div class="post_name">{{ post.author }}</div>
				<div class="post_location">London Ontario</div>
			</div>
			<div class="post_options"><i class="fas fa-ellipsis-h"></i></div>
		</div>
		<div class="post_image">
			{% if post.image %}
			<img src="{{ post.image.url }}" alt="">
			{% endif %}
		</div>
		<div class="engagement">
			<a href=""><i class="far fa-heart"></i></a>
			<a href=""><i class="far fa-comment"></i></a>
			<a href=""><i class="far fa-share-square"></i></a>
			<a href=""><i class="far fa-bookmark"></i></a>
	</div>
	<div class="likes">
		<a href="">12</a>
	</div>
	<div class="caption">
		<a href=""><h2>{{post.author}}</h2></a>
		<span> <p> {{post.caption}} </p> </span>
	</div>
	<div class="time_posted">
		{{ post.created_date | timesince }} ago
	</div>
</div>
<!-- begin wwww.htmlcommentbox.com -->
 <div id="HCB_comment_box"><a href="http://www.htmlcommentbox.com">Comment Form</a> is loading comments...</div>
 <link rel="stylesheet" type="text/css" href="https://www.htmlcommentbox.com/static/skins/bootstrap/twitter-bootstrap.css?v=0" />
 <script type="text/javascript" id="hcb"> /*<!--*/ if(!window.hcb_user){hcb_user={};} (function(){var s=document.createElement("script"), l=hcb_user.PAGE || (""+window.location).replace(/'/g,"%27"), h="https://www.htmlcommentbox.com";s.setAttribute("type","text/javascript");s.setAttribute("src", h+"/jread?page="+encodeURIComponent(l).replace("+","%2B")+"&mod=%241%24wq1rdBcg%24wpLbkkJlgz3%2FEO0Cgy6V5."+"&opts=16850&num=10&ts=1582256084247");if (typeof s!="undefined") document.getElementsByTagName("head")[0].appendChild(s);})(); /*-->*/ </script>
<!-- end www.htmlcommentbox.com -->

<!-- 	{% endfor %} -->
{% endblock %}

poster/templates/poster/poster_create.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}

<div class="container">
  <h1>Create new poster</h1>
  {% csrf_token %}
  <form method="post" style="margin-top: 1.3em;" enctype='multipart/form-data'>
      {{ form | crispy }} 
      {% csrf_token %}
      <button class="btn btn-primary" type="submit">Create</button>
    </form>
</div

{% endblock %}

poster/templates/poster/poster_detail.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<div class="container" id="poster">
  <h1>{{ poster.title }}</h1>
  <h2>{{ poster.subtitle }}</h2>
  <div class="container" id="poster-image">
    <img
      src="{{ poster.image.url }}"
      class="img-fluid"
      alt="Responsive image"
    />
  </div>
</div>
<br />
<div class="container" id="poster-description">
  <h2>Description</h2>
  <p>{{ poster.description }}</p>
  {% if is_editable %}
    <a href="{% url 'poster:poster_update' conference.id poster.id %}">Edit Poster</a>
  {% endif %}
</div>
<br />
<div class="container" id="poster-comments">
  <h2>Comments</h2>
  {% for comment in comments %}
  <div class="comments" style="padding: 10px;">
    <a href="{% url 'core:profile' comment.author.username %}"
      ><img
        class="rounded-circle img-fluid"
        style="height: 64px;"
        src="{{ comment.author.avatar.url }}"
        alt=""
    /></a>
    <p class="font-weight-bold">
      <a href="{% url 'core:profile' comment.author.username %}"
        >{{ comment.author.first_name }} {{ comment.author.last_name }}</a
      >
      <span class="text-muted font-weight-normal">
        {{ comment.created_date }}
      </span>
    </p>
    {{ comment.body | linebreaks }}
  </div>
  {% endfor %} {% if user.is_authenticated %}
  <div class="card-body">
    {% if new_comment %}
    <div class="alert alert-success" role="alert">
      Comment posted
    </div>
    {% elif can_comment %}
      <h3>Leave a comment</h3>
      {% load crispy_forms_tags %}
      <form method="post" style="margin-top: 1.3em;">
        {{ comment_form | crispy }} {% csrf_token %}
        <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    {% endif %}
  </div>
  {% else %}
  <p>
    <a href="{% url 'account_signup' %}">Sign up</a> or
    <a href="{% url 'account_login' %}">login</a> to comment.
  </p>
  {% endif %}
</div>

{% endblock %}